import Head from "next/head";
import axios from "axios";

import SliderSection from "../components/shared/SliderSection";
import FeaturesSection from "../components/shared/FeaturesSection";
import BlogsSection from "../components/shared/BlogsSection";
import HomeHeroSection from "../components/home/HomeHeroSection";
import HomeCollectionsSection from "../components/home/HomeCollectionsSection";
import HomeProductSection from "../components/home/HomeProductSection";
import HomeAboutSection from "../components/home/HomeAboutSection";

// import styles from "../styles/Home.module.scss";
import HomeFeaturedProductSection from "../components/home/HomeFeaturedProductSection";

export default function Home({ recentProducts, collections }) {
  return (
    <div>
      <Head>
        <title>Jwellery Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHeroSection />

      <FeaturesSection />

      <SliderSection
        headingLabel="The Bestsellers"
        recentProducts={recentProducts}
      />

      <HomeProductSection />

      <SliderSection
        headingLabel="Trending Products"
        recentProducts={recentProducts}
      />

      <HomeAboutSection />

      <HomeFeaturedProductSection
        recentProducts={recentProducts}
        isFeatured={true}
      />

      <HomeCollectionsSection collections={collections} />

      <BlogsSection />
    </div>
  );
}

export const getServerSideProps = async () => {
  const response = await axios.get("http://offerkcha.com/api/recent");
  const recentProducts = await response.data.data;

  const response2 = await axios.get("http://offerkcha.com/api/category");
  const collections = await response2.data.data;

  return {
    props: {
      recentProducts,
      collections,
    },
  };
};
