import Head from "next/head";
import SliderSection from "../components/shared/SliderSection";

import FeaturesSection from "../components/shared/FeaturesSection";
import BlogsSection from "../components/shared/BlogsSection";
import HomeHeroSection from "../components/home/HomeHeroSection";
import HomeCollectionsSection from "../components/home/HomeCollectionsSection";
import HomeProductSection from "../components/home/HomeProductSection";
import HomeAboutSection from "../components/home/HomeAboutSection";

// import styles from "../styles/Home.module.scss";
import HomeFeaturedProductSection from "../components/home/HomeFeaturedProductSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jwellery Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHeroSection />

      <FeaturesSection />

      <SliderSection headingLabel="The Bestsellers" />

      <HomeProductSection />

      <SliderSection headingLabel="Trending Products" />

      <HomeAboutSection />

      <HomeFeaturedProductSection />

      <HomeCollectionsSection />

      <BlogsSection />
    </div>
  );
}
